name: Testing Suite

on: push

jobs:
  testing_job:
    name: Main Testing job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      
      - name: Install Python and requirements
        uses: actions/setup-python@v6.1.0
        with: 
          python-version: '3.12.10'
          cache: 'pip'
        run: pip install -r requirements.txt
      
      - name: Configure Playwright
        run: playwright install  